
import os
SERVER_SECRET = os.environ['SERVER_SECRET']
DB2_URL =  os.environ['DB2_URL']
COURIER_AUTH_KEY =  os.environ['COURIER_AUTH_KEY']

MAIN_SERVER_REDIRECT_URL = os.environ['MAIN_SERVER_REDIRECT_URL']

