import os

SERVER_SECRET = os.environ['SERVER_SECRET']
AUTH_SERVER_URL = os.environ['AUTH_SERVER_URL']
AUTH_SERVER_REDIRECT_URL = os.environ['AUTH_SERVER_REDIRECT_URL']

# API
SPOONACULAR_BASE_URL = os.environ['SPOONACULAR_BASE_URL']
SPOONACULAR_API_KEY = os.environ['SPOONACULAR_API_KEY']

# IBM
DB2_URL = os.environ['DB2_URL']
COS_ENDPOINT = os.environ['COS_ENDPOINT']
COS_API_KEY_ID =  os.environ['COS_API_KEY_ID']
COS_INSTANCE_CRN = os.environ['COS_INSTANCE_CRN']

